/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "RemotionTang": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "RemotionTest": {
      "bucketName": string
      "functionName": string
      "region": string
      "siteUrl": string
      "type": "pkg.index.RemotionLambda"
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TursoUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
